---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3205
  namespace: redhat-citrix
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "vlan3205",
        "type": "bridge",
        "bridge": "br3205",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false,
        "vlan": 3205
    }

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3205
  namespace: redhat-citrix-cloud
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "vlan3205",
        "type": "bridge",
        "bridge": "br3205",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false,
        "vlan": 3205
    }
